# <span style="color:red; font-size:25px"> DATASCI 151 - Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

<!-- - This is a graded quiz. Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED. </span> -->

- AI assistance is <span style="color:red"> NOT </span> permitted for this assignment.

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [32]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "4">

Import any packages you would like in the cell below. Or, import them as needed later in the notebook.

In [33]:
# import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories. (**Both** endpoints are included in the listed categories)

    - **Silent Era**: Films made between 1917 and 1927

    - **Golden Age**: Films made between 1928 and 1949

    - **Post-War**: Films made between 1950 and 1964

    - **New Hollywood**: Films made between 1965 and 1974

    - **Blockbuster Era**: Movies made between 1975 and 2000

    - **Digital Age**: Movies made between 2001 until the present

- You must use the `pd.cut` function to recode this variable.

- Add a new column to the DataFrame called "Era" that contains this recoded variable.

In [34]:
# your code here
df = pd.read_csv("quiz_data/movies.csv")

year_bins = [1917, 1927, 1949, 1964, 1974, 2000, np.inf]
year_labels = ["Silent Era", "Golden Age", "Post-War", "New Hollywood", "Blockbuster Era", "Digital Age"]


df["Era"] = pd.cut(x = df["Year"], 
                bins=year_bins, 
                labels = year_labels)
display(df.sort_values(by = "Year"))

,Title,IMDb rating,Year,MPA rating,Genre,Director,Star Cast,MetaScore,Duration (minutes),Era
3835,She,6.9,1917,R,Drama,Kenean Buel,Valeska SurattBen TaggartMiriam Fouche,66.0,116.3,NaN
1090,"Homunculus, 6. Teil - Das Ende des Homunculus",6.7,1917,R,Drama,Otto Rippert,Olaf FønssFriedrich KühneMechthildis Thein,66.0,116.3,NaN
1456,A léleklátó sugár,5.3,1918,R,Sci-Fi,Alfréd Deésy,Daniel RadcliffeEmma WatsonRupert Grint,66.0,116.3,Silent Era
67,The Kid,8.2,1921,Other,Comedy,Charles Chaplin,Charles Chaplin,57.1,68.0,Silent Era
2067,The City Struck by Lightning,5.7,1924,R,Sci-Fi,Luitz-Morat,Daniel MendailleJane MaguenatArmand Morins,66.0,116.3,Silent Era
...,...,...,...,...,...,...,...,...,...,...
342,Harold and the Purple Crayon,7.1,2024,PG,Animation,Carlos Saldanha,Zachary LeviLil Rel HoweryBenjamin Bottani,66.9,92.0,Digital Age
3110,Orion and the Dark,6.3,2024,Other,Animation,Sean Charmatz,Jacob Tremblay,72.0,93.0,Digital Age
1491,Under Paris,6.9,2024,R,Action,Xavier Gens,Sebastien AuscherYannick DahanXavier Gens,66.0,116.3,Digital Age
1247,Minecraft,7.1,2025,R,Action,Jared Hess,Chris BowmanHubbel PalmerAllison Schroeder,66.9,116.3,Digital Age
2115,Blade,6.9,2025,R,Action,Yann Demange,Gene ColanMichael GreenStacy Osei-Kuffour,66.0,116.3,Digital Age

<font size = "4">

**Q2** Conditional Subsetting

<font size = "3">

- Continue to use the movies DataFrame from Q1 (or read it in again)

- Return a DataFrame with the **6 shortest movies** that (a) were released 2011 or later, and (b) have IMDb rating of 6.0 or greater.

**Hint**: The column containing the IMDb rating is named "IMDb rating", which would not be a valid Python variable because of the space. If this causes you trouble and you don't remember how to handle it, you could simply rename the column to "IMDb_rating".

In [35]:
# your code here
df.rename({"IMDb rating": "IMDb_rating"}, inplace = True)
filtered_df = df[(df["Year"] >= 2011) & (df["IMDb rating"] >= 6.0)]

<font size = "4">

**Q3** Aggregating Group Statistics with Chaining

<font size = "3">

- Continue to use the movies DataFrame from Q1 (or read it in again)

- The column "MPA rating" shows whether the movie was rated R, PG-13, etc. Aggregate the following statistics for each MPA rating:

    - Mean IMDb rating

    - Median duration (in minutes)

- Sort the resulting DataFrame by mean IMDb rating in **ascending** order.

- For full credit, execute all commands on a single line by chaining

In [43]:
# your code here
df_agg = df.groupby(by="MPA rating"
                    ).agg(mean_rating = ("IMDb rating", "mean"),
                           median_duration = ("Duration (minutes)", "median")
                           ).sort_values(by = "mean_rating", ascending = True)

<font size = "4">

**Q4** Calculate laps per minute

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $6 \times 10^{-4}$

- Create a new column called "laps_per_minute" which is calculated by the formula: $\ \dfrac{\textrm{laps}}{\textrm{race\_duration\_minutes}}$

- Group the data by **both** "raceId" and "driverId" and calculate the **maximum laps per minutes** for each group.

- Sort the data in descending order and then extract the raceId/driverId pairs with the 5 highest laps per minute

<br>

**Hint**: For a Pandas Series, the `.sort_values()` method does **not** take the keyword "by".

In [40]:
# your code here
df_results = pd.read_csv("quiz_data/results_cleaned.csv")

df_results["laps_per_minute"] = df_results["milliseconds"] / 6e4

gb = df_results.groupby(["raceId", "driverId"])

gb["laps_per_minute"].max().sort_values(ascending=False).head(5)

raceId  driverId
818     729         251.509000
        728         249.625500
        727         248.783000
        658         247.060000
        593         246.327667
Name: laps_per_minute, dtype: float64

<font size = "4">

**Q5** Aggregate and query

<font size = "3">

- Continue to use the "results_cleaned.csv" DataFrame from Q4 (or read it in again)

- Do the following in a single line using chaining:

    - Extract the subset with raceId equal to 21.

    - Aggregate the minimum number of points and average number of points for each constructor in the subset.

    - Extract the subset of these constructors with average number of points **strictly greater than 1**

In [44]:
# your code here
df_agg = df_results[df_results["raceId"] == 21].groupby("constructorId").agg(min_points=("points", "min"),mean_points=("points", "mean")).query("mean_points > 1")

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv" (or read it in again).

- We might consider it a "bad day" for an F1 driver if they finish outside the top ten (11th or worse). Write a function that takes in a Pandas Series and returns the number of entries $ > 10$.

- Group by "driverId" and then aggregate the following statistics based on the "positionOrder" column: the average (mean) position and the number of finishes outside the top ten.

- Use your custom function for this second statistic.

- Merge the aggregated data back **into the original DataFrame**.

In [31]:
# your code here
def finishes(col):
    return (col <= 10).sum()
df_agg = df_results.groupby(by="driverId").agg(avg_position = ("positionOrder", "mean"),
                                      finishes = ("positionOrder", finishes))

df_results = pd.merge(left = df_results, right = df_agg, on = "driverId", how = "left")

df_results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,laps_per_minute,avg_position,finishes
0,1,18,1,1,22,1,1,1,1,10.0,...,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1,94.843600,4.707641,264
1,2,18,2,2,3,5,2,2,2,8.0,...,+5.478,5696094.0,41,3,1:27.739,217.586,1,94.934900,10.722826,101
2,3,18,3,3,7,7,3,3,3,6.0,...,+8.163,5698779.0,41,5,1:28.090,216.719,1,94.979650,8.252427,144
3,4,18,4,4,5,11,4,4,4,5.0,...,+17.181,5707797.0,58,7,1:28.603,215.464,1,95.129950,8.409742,233
4,5,18,5,1,23,3,5,5,5,4.0,...,+18.014,5708630.0,43,1,1:27.418,218.385,1,95.143833,13.285714,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,...,\N,NaN,37,15,1:23.511,188.856,11,NaN,13.172932,40
25656,25662,1086,848,3,23,17,17,17,17,0.0,...,\N,NaN,43,12,1:23.047,189.911,11,NaN,10.137255,27
25657,25663,1086,849,3,6,19,18,18,18,0.0,...,\N,NaN,60,8,1:22.478,191.221,11,NaN,15.730769,2
25658,25664,1086,852,213,22,16,19,19,19,0.0,...,\N,NaN,58,16,1:23.538,188.795,12,NaN,13.657143,10
25659,25665,1086,822,51,77,8,20,20,20,0.0,...,\N,NaN,60,19,1:24.002,187.752,131,NaN,7.281250,139